"""Add is_pending to users table

Revision ID: 66322f1ee3d3
Revises: db6fd4707b58
Create Date: 2018-04-21 18:34:30.316321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66322f1ee3d3'
down_revision = 'db6fd4707b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
